### ISSUE TITLE
Modulo para controlar el motor

### ISSUE THREAD

**Issue by Santtiago98** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil#1]
[Aquí ](https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil/blob/master/codigo/motor.asm) se encuentra el módulo que diseñamos para controlar el movimiento de la plataforma. 

Dudas:
¿Conviene llamar a GIRAR_DERECHA/IZQUIERDA como una rutina o simplemente un rjmp?
¿Es correcto el seteo para prender/apagar el motor?
¿Alguna mejora que se pueda implementar?

**Comment by rarias** [comment]
Eso depende...
Pero está mal su código, si van con RJMP no pueden terminar con un RET (aprobaron el parcial?!)

**Comment by Santtiago98** [comment]
En un principio era un RCALL (por eso el RET) pero de ahí surgió la 1er pregunta, si era más conveniente que sea tratarlo como JMP o rutina. 
Lo dejamos como rutina.

Gracias
