### ISSUE TITLE
girar derecha/izquierda

### ISSUE THREAD

**Issue by rarias** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil#3]
En general, uno tiene una variable de estado, llamémosla AVANCE y se actualiza cuando ocurren los cambios de los sensores. Para para que el movimiento sea mas parejo, o sin saltos, uno "filtra" la información de los sensores antes de confirmar el estado AVANCE, por ejemplo de HACIA_ADELANTE a HACIA_IZQDA.   El "filtro" puede ser simplemente que a la tercera vez que se confirmó el valor de los sensores, se hace el cambio de estado.   Esto además implica que los sensores se observan usando una base de tiempo regular, digamos cada 20uS, y este tiempo lo marca un timer típicamente.
   Cada vez que el timer interrumpe (cada 20uS) se miran los sensores, se filtra (o no, para empezar), y si ocurre el cambio de dirección, se informa mediante un FLAG al main que debe cambiar AVANCE.
  Desde MAIN, al cambiar el estado AVANCE, se invoca a una rutina (una sóla rutina) que recibe la variable global AVANCE y modifica la acción del motor.   Esta no es más que un switch(AVANCE) case IZQ, ..., case DCH, etc. que se implementa con JUMPs.

**Comment by rarias** [comment]
La otra opción, tal vez más cercana a lo que están planteando en su código, es que el timer actualice el estado del SENSOR y main todo el tiempo esté mirando esa variable,  decidiendo cambiar el estado de AVANCE según corresponda, y luego invoque a LA rutina que maneja los motores.

**Comment by rarias** [comment]
De cualquier forma que lo hagan, es conveniente desacoplar el mirar los pines del sensor y manejar los puertos del motor/es.   Esto permite mejorar el sensado en un rutina (tal vez la misma ISR del timer) y la acción de los motores, en otra (por ejemplo en el caso de motores que se tienen que controlar la velocidad de aceleración, que no es su caso).

**Comment by Santtiago98** [comment]
Gracias por el comentario Ricardo.
Entiendo perfectamente lo que decis, seria implementar una lógica distinta a como lo estamos haciendo de momento -mirar los sensores dentro de la función del motor en vez de hacerlo dentro de MAIN. 
Me surge una duda respecto del sensado. Me queda claro que con esta nueva lógica lo del "filtrado" previo lo hace más robusto, es un caso que no habiamos contemplado, pero el funcionamiento del mismo como seria? El timer funcionaria como interrupción y vendría cada T tiempo a mirar los pines? O es una configuración diferente a interrupción?
Muchas gracias nuevamente!

**Comment by rarias** [comment]
Sí, el timer interrumpe y se miran los pines, comparando con el estado anterior (de esos pines).
Es una especie de "anti-rebotes" (debouncing) de los sensores.
