### ISSUE TITLE
problema con avance inicial; redefinir con .SET

### ISSUE THREAD

**Issue by dengayet** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil#8]
Buenas, estamos teniendo un problema con el código porque al resetear el arduino, si los sensores están en el valor correcto los motores arrancan sin ser llamados. Una vez que frenan sólo vuelven a arrancar si son llamados. Tratamos de solucionarlo seteando los motores a 0 al inicio pero igualmente arrancan. Suponemos que el error está en que se da la interrupción al iniciar el programa -que no debería porque no fue llamado aún-, pero no sería posible porque la única forma de que entre a avanzar es haber mandado un valor específico a RX.
Por otro lado, para la retirada lo que hacemos es redefinir los valores que toman las etiquetas con .SET para reutilizar el código, pero no tiene efecto ya que toma los valores de los .SET que están más arriba en el código. ¿Estamos usando la directiva 

Muchas gracias

código:
https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil/blob/master/codigo/

**Comment by fbaglivo** [comment]
Hola @dengayet! El código parece que esta ok. El problema solo lo tenes al resetear o cuando lo apagas y prendes también? Por las dudas, apaga todas las interrupciones usando CLI luego de inicializar el stack. 

Me seria muy útil poder ver el esquemático circuital y un diagrama de flujos para entender la causa. Los motores son de continua o paso a paso o servo? Se encienden con '1'? También deben agregarle un encabezado a cada rutina explicando que hace, que recibe como input y que saca como output.

Por otro lado, veo que hacen todo dentro de la rutina de interrupción. Eso complica el seguimiento. Seria mejor que lo implemente como maquina de estados. Ahora hagan andar el equipo así como esta, pero considérenlo una mejora.

En cuanto al .SET, por que no definen las etiquetas al inicio principio del programa? Eso mejoraría la legibilidad del código, y después pueden poner un .SET para cambiarlas cuando lo necesiten.
 Si esas etiquetas se definieron siempre con .SET no debería haber problema. Están seguros que no esta andando?

Saludos!

Fabricio

**Comment by Santtiago98** [comment]
Hola Fabricio,
El problema surge siempre que reseteamos el programa con el botón de Arduino.
Si aún no activamos las interrupciones, por qué o en qué afectaría apagar las interrupciones con CLI luego de inicializar el stack?
Los motores son dos, de continua, y se encienden enviando un 1 a unos de los pines control y un 0 al otro. Cada motor tiene dos pines de control y variando cuál se active se altera la dirección de giro de la rueda. Es ese el motivo por el cual los .SET no se hacen al inicio y se hacen dentro de las funciones para avanzar o retroceder. Porque de esta manera podriamos modificar la etiqueta que la rutina que controla los motores utiliza para activarlos (MOTOR_IZQ_0 y MOTOR_DER_0). Es decir, cuando se va hacia adelante esas etiquetas estarán asignadas al pin que tenga el '1' pero para ir en reversa el '1' debe estar ahora en el otro pin, y para no reescribir la rutina entera, intentamos redefinir esas variables. Pero por lo que observamos parecería ser que el redefine no surge efecto porque los motores se mueven siempre en la direccion de la rutina (avanzar o retroceder) que esté escrita primera en el código.

¿Qué sería hacerlo andar como máquina de estados?

[Acá](https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Tacho-movil/blob/master/doc/diagramas/Diagrama_de_flujo_smarTTrash.pdf) está el diagrama de flujo del programa actual.
Quitando el error del inicio, el robot 'anda bien' pero en una dirección sola, es decir ambas directivas que le mandamos, ya sea reversa o avanzar, producen el mismo efecto.

Gracias por la respuesta y saludos!

**Comment by fbaglivo** [comment]
Consultas:

Ustedes están manejando el movimiento del robot desde la rutina de interrupción...que pasa si entra otra interrupción mientras se están moviendo?  Estan anidando interrupciones. Es riesgoso y dificil de seguir. Por eso les decia de hacer maquinas de estado. En este caso en la interrupción se fijan el estado de los sensores y cambian el estado (el valor de una variable), pero no accionan sobre los motores. Cuando vuelven al main se fijan en que estado estan y accionan en funcion de eso. Por ejemplo tendrian un estado "Frenar", otro "AVANZAR" y otro "RETROCEDER". De esa manera pueden tener mas control de lo que esta pasando.

Por otro lado, esto esta bien?:

       RJMP GIRAR_DERECHA ;si SENSOR_DER = 1 -> gira a la DERECHA
	SBIC PORT_MOTOR, SENSOR_IZQ ;si sensor_der dio 1, sensor_izq sera 0
	RCALL GIRAR_IZQUIERDA ;

GIRAR_DERECHA la llaman con un RJMP y GIRAR_IZQUIERDA con un RCALL. Ambas vuelven con RJMP LOOP. 

Estan seguro que en su implementación se están llamando tanto AVANZAR como RETROCEDER? Es raro que el .SET no este funcionando. Puede ser que lo que pase es que una de las rutina nunca se este llamando? Por otro lado, tal vez les convenga usar MACROS para estas rutinas, pasandole como parámetro los registros que quieren usar. O al menos que sean rutinas.

Saludos!

Fabricio

**Comment by Santtiago98** [comment]
Comprendo la idea de trabajar como máquina de estados, la vamos a tener en cuenta.
En cuanto a lo de interrupciones anidadas, tenia entendido que en el momento en que saltó una interrupción no se va a generar otra hasta salir con RETI o hasta habilitarlas manualmente. Nosotros no las habilitamos dentro de la interrupción, por lo cual no veo cómo podriamos caer en el caso de interrupciones anidadas.
Con respecto a esto, no estoy seguro de que esté funcionando bien la interrupcion del RX, probando el codigo por separado lo que observo es que nunca se sale de la rutina de interrupción. Lo pruebo prendiendo y apagando un led, es decir parpadeando con un intervalo de 3seg aprox y esto se realiza de forma repetitiva siempre. Lo que sólo ocurriría sólo si entrara siempre a la rutina de interrupción, es decir que no está funcionando bien la relacion con el módulo bluetooth.
Este sería el sencillo código del que estoy hablando, en el cual observo el 'bug'.

`   .include "m328pdef.inc"
    .DEF AUX=R16
    .CSEG 
    .ORG 0X00
    RJMP MAIN
    .org URXCaddr
    RJMP ISR_USART

    .ORG INT_VECTORS_SIZE

    MAIN:
	LDI R16, LOW(RAMEND)
	OUT SPL, R16
	LDI R16, HIGH(RAMEND)
	OUT SPH, R16

	RCALL USART_INIT
	;rcall delay
	SEI

    LOOP:
	RJMP LOOP

    ISR_USART:
	RCALL USART_ENVIAR
	RETI

    USART_ENVIAR:
	LDS R18, UCSR0A
	SBRS R18, UDRE0
	RJMP USART_ENVIAR
	; led de prueba
	sbi ddrd, pind7
	sbi portd, pind7 ;on led
	rcall delay
	cbi portd, pind7
	rcall delay
	;---+
	LDI R16, '9' ;lo que quiero enviar
	;STS UDR0, R16 ;aca lo envio
	
	RET

    USART_INIT:
	;seteo los baudios
	clr AUX
	STS UBRR0H, AUX
	LDI AUX, 0x67
	STS UBRR0L, AUX
	;habilito emision y transmision
	clr AUX
	LDI AUX, (1<<RXEN0)|(1<<TXEN0)|(1<<RXCIE0)
	STS UCSR0B, AUX
	;seteo formato: 8data, 2bit de stop
	LDI AUX, (1<<USBS0)|(1<<UCSZ00)|(1<<UCSZ01)
	STS UCSR0C, AUX
	RET

    delay:
    ldi  r18, 3
    ldi  r19, 57
    ldi  r20, 46
    ldi  r21, 130
    L1: dec  r21
    brne L1
    dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
	ret` 

En resumen, no podria garantizar que se esté llamando tanto a AVANZAR como a RETROCEDER ya que un simple testeo de la configuración de la interrupción presenta errores.

> GIRAR_DERECHA la llaman con un RJMP y GIRAR_IZQUIERDA con un RCALL. Ambas vuelven con RJMP LOOP.

Corregido, muchas gracias por la revisión.

Gracias y saludos!

**Comment by fbaglivo** [comment]
Pregunta rápida (desde el celular)...cuanto tarda en ejecutarse la rutina
delay? La probaron por separado?

Lo que decis de la interrupción es verdad pero si no las habilitar...como
haces para abortar una acción? Así como esta perdes flexibilidad
(usabilidad).

**Comment by Santtiago98** [comment]
El delay del código que pegué más arriba tarda aprox 6/7 segs, funciona correctamente, el led parpadea, pero como dije, lo hace de forma indefinida, o sea nunca sale de la rutina esa (o siempre salta la interrupción, lo cual sería muy raro) Además, si desconecto el cable Rx y lo conecto salta inmediatamente la interrupción (lo cual tendria sentido pq hay 1.8 V por default entre OUT-bluetooth y GND, podria llegar a interpretarse como un flanco ascendente). ¿Quizá se quemó el módulo bluetooth? ¿ Es posible este comportamiento? Cuando envio señal con el celular observo 30 mV de variación, midiendo con un multímetro en AC, ya haré la prueba con un osciloscopio para estar seguro.

Gracias nuevamente Fabricio,
Saludos!

Santiago.-

**Comment by fbaglivo** [comment]
Hola Santiago, los modulos esos se pueden quemar (sucedio varias veces). Deberias poder debuggear si nunca sale de la interrupcion on si el problema es que se vuelve a llamar automaticamente. Togglea un led en el main y te vas a dar cuenta. Tambien podes togglear un led en la interrupcion y ver comportamiento.
